from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, JSON, Text
from app.db.base_class import Base

class TokenUnlockEvent(Base):
    __tablename__ = "token_unlock_events"

    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String, index=True, nullable=False)
    token_name = Column(String, nullable=True)
    unlock_date = Column(DateTime, index=True, nullable=False)
    amount = Column(Float, nullable=False)
    amount_usd = Column(Float, nullable=False)
    circulating_supply_pct = Column(Float, nullable=True)
    
    # Storing complex structures as JSON
    vesting_schedule = Column(JSON, nullable=True)  # e.g., [{"date": "...", "amount": ...}]
    allocations = Column(JSON, nullable=True)       # e.g., [{"name": "Team", "pct": 10}]
    
    # Analysis & Meta
    impact_score = Column(Float, nullable=True)     # Calculated metric
    ai_summary = Column(Text, nullable=True)        # Generated by Gemini
    is_verified = Column(Boolean, default=False)
