import asyncio
import sys
import time
import os

# Add the project root to python path to import app modules
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from app.db.session import SessionLocal
from app.models.bot import Bot
from app.strategies.wall_hunter_futures import WallHunterFuturesStrategy

async def test_notification():
    db = SessionLocal()
    # Find a valid bot record
    bot_record = db.query(Bot).first()
    if not bot_record:
        print("No bot records found in the database. Cannot send a real test notification.")
        return
        
    print(f"Using Bot ID: {bot_record.id}, Name: {bot_record.name}, Owner ID: {bot_record.owner_id}")

    # Mock ccxt_service
    class MockEngine:
        pass

    # Instantiate the strategy
    strategy = WallHunterFuturesStrategy(bot_record, MockEngine())
    
    # Fake active position with entry_time set to 1 hour, 5 mins and 12 seconds ago
    fake_entry_time = time.time() - (3600 + 5 * 60 + 12)
    strategy.active_pos = {
        'side': 'long',
        'entry': 0.105640,
        'amount': 1000,
        'tp': 0.105620,
        'tp1': 0.105630,
        'sl': 0.105800,
        'entry_time': fake_entry_time
    }
    
    strategy.total_realized_pnl = 0.0812345
    strategy.total_wins = 4
    strategy.total_losses = 0

    print("\n--- Sending Entry Message ---")
    trade_type = "Long"
    entry_msg = (
        f"⚡ WallHunter Entered!\\n"
        f"Bot Name: {strategy.bot_name}\\n"
        f"Bot ID: {strategy.bot_id}\\n"
        f"Trade Types: {trade_type}\\n"
        f"Pair: {strategy.symbol}\\n"
        f"Entry {strategy.active_pos['entry']:.6f}\\n"
        f"TP1: {strategy.active_pos['tp1']:.6f}\\n"
        f"Final TP: {strategy.active_pos['tp']:.6f}\\n"
        f"SL: {strategy.active_pos['sl']:.6f}"
    )
    await strategy._send_telegram(entry_msg)
    print(entry_msg)

    print("\n--- Sending Exit Message ---")
    await strategy._send_exit_telegram(
        title="🎯 Futures EXIT - Limit TP Filled! (TEST RUN)", 
        filled_price=0.105620, 
        pnl_val=0.0157845
    )
    print("Exit message generated by strategy method.")
    
    db.close()
    print("\n✅ Test Notifications Sent Successfully! Check your Telegram.")

if __name__ == "__main__":
    asyncio.run(test_notification())
