import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { IndicatorSettings } from '@/components/features/market/IndicatorSelector';

interface BotState {
    activeWallHunterId: number | null;
    setActiveWallHunterId: (id: number | null) => void;
    indicatorSettings: IndicatorSettings;
    setIndicatorSettings: (settings: IndicatorSettings) => void;
}

export const useBotStore = create<BotState>()(
    persist(
        (set) => ({
            activeWallHunterId: null,
            setActiveWallHunterId: (id) => set({ activeWallHunterId: id }),
    indicatorSettings: {
        showEMA: false,
        showBB: true,
        showRSI: false,
        showMACD: false,
        showVolume: false,
        showAutoFibo: false,
        showIchimoku: false,
        showTrendFinder: false,
        showUTBot: false,
        showSessions: false,
        aetherHull: false,
        aetherOrderBlocks: false,
        aether3BarReversal: false,
        aetherAutoFibo: false,
        emaPeriod: 20,
        bbPeriod: 20,
        bbStdDev: 2,
        rsiPeriod: 14,
        macdFast: 12,
        macdSlow: 26,
        macdSignal: 9,
        autoFiboLookback: 50,
        tenkanPeriod: 9,
        kijunPeriod: 26,
        senkouBPeriod: 52,
        displacement: 26,
        trendFinderLookback: 30,
        trendFinderDev: 2.0,
        trendFinderThreshold: 'Strong',
        enableTrendFinderVolumeFilter: false,
        trendFinderVolumeMultiplier: 1.5,
        hideLowConfidenceTrend: false,
        utBotSensitivity: 1,
        utBotAtrPeriod: 10,
        utBotUseHeikinAshi: false,
        sessionA: { show: true, name: 'New York', session: '1300-2200', color: '#ff5d00', showRange: true, showTrendline: false, showMean: false, showVWAP: false, showMaxMin: false },
        sessionB: { show: true, name: 'London', session: '0700-1600', color: '#2157f3', showRange: true, showTrendline: false, showMean: false, showVWAP: false, showMaxMin: false },
        sessionC: { show: true, name: 'Tokyo', session: '0000-0900', color: '#e91e63', showRange: true, showTrendline: false, showMean: false, showVWAP: false, showMaxMin: false },
        sessionD: { show: true, name: 'Sydney', session: '2100-0600', color: '#ffeb3b', showRange: true, showTrendline: false, showMean: false, showVWAP: false, showMaxMin: false },
        timezoneOffset: 0,
        rangeTransparency: 10,
        showOutline: true,
        showSessionLabel: true,
        showSessionDashboard: true,
        advancedDashboard: false,
        // Smart Money Concepts defaults
        showSMC: false,
        smcStyle: 'Colored',
        smcMode: 'Historical',
        smcShowInternals: true,
        smcInternalBullFilter: 'All',
        smcInternalBearFilter: 'All',
        smcConfluenceFilter: false,
        smcShowSwing: true,
        smcSwingBullFilter: 'All',
        smcSwingBearFilter: 'All',
        smcSwingLength: 50,
        smcShowStrongWeakHL: true,
        smcShowInternalOB: true,
        smcInternalOBCount: 5,
        smcShowSwingOB: false,
        smcSwingOBCount: 5,
        smcOBFilter: 'Atr',
        smcOBMitigation: 'High/Low',
        smcShowEqualHL: true,
        smcEqualHLLength: 3,
        smcEqualHLThreshold: 0.1,
        smcShowFVG: false,
        smcFVGAutoThreshold: true,
        smcFVGExtendBars: 1,
        smcShowPDZones: false,
        smcL2Validation: true,
        smcCVDTrap: true,
        smcMicroFVG: true,
        smcSweepDetection: true,
        smcShowSwingPatterns: true,
        // Dual Engine Defaults
        showDualEngine: false,
        dualEngineEmaPeriod: 50,
        dualEngineRsiPeriod: 14,
        dualEngineRsiOB: 70,
        dualEngineRsiOS: 30,
        dualEngineMacdFast: 12,
        dualEngineMacdSlow: 26,
        dualEngineMacdSignal: 9,
        dualEngineSqueezeLength: 20,
        dualEngineSqueezeBB: 2.0,
        dualEngineSqueezeKC: 1.5,
        dualEngineMode: 'Hybrid', // 'Hybrid' | 'Legacy'
        dualEngineAdxLength: 14,
        dualEngineAdxThreshold: 25,
        fredApiKey: '',
        showWatchlistScanner: false,
        // ── ICT Killzones & Pivots [TFO] ──
        showICTKillzones: false,
        ictShowPivots: true,
        ictPivotsExtend: 'Until Mitigated',
        ictShowDWM: true,
        ictShowDailyOpen: true,
        ictShowWeeklyOpen: false,
        ictShowMonthlyOpen: false,
        ictShowMidnightOpen: true,
        ictShowOpeningPrices: false,
        ictShowTimestamps: false,
        ictAsiaSession: '2000-0000',
        ictLondonSession: '0200-0500',
        ictNyAmSession: '0930-1100',
        ictNyLunchSession: '1200-1300',
        ictNyPmSession: '1330-1600',
        ictShowSilverBullet: false,
        ictShowConfluence: false,
        ictShowAMD: false,
        ictShowGaps: false,
        ictShowVolatility: false,
        ictShowEquilibrium: false,

        luxShowIndicator: false,
        luxMode: 'Present',
        luxShowMS: true,
        luxSwingLength: 5,
        luxShowMSS: true,
        luxShowBOS: true,
        luxShowDisplacement: false,
        luxPercBody: 0.36,
        luxShowVIMB: true,
        luxVIMBThreshold: 2,
        luxShowOB: true,
        luxOBLookback: 10,
        luxShowBullOB: 1,
        luxShowBearOB: 1,
        luxShowOBLabels: false,
        luxShowLiq: true,
        luxLiqMargin: 2.5, // 10/4
        luxLiqVisibleCount: 2,
        luxShowFVG: true,
        luxBPR: false,
        luxFVGType: 'FVG',
        luxFVGVisibleCount: 2,
        luxShowNWOG: true,
        luxNWOGMax: 3,
        luxShowNDOG: false,
        luxNDOGMax: 1,
        luxFibMode: 'NONE',
        luxFibExtend: false,
        luxShowKillzones: false,
        // ── Quantum AI v8 ──
        showQuantumAI: false,
        quantumMinConf: 70,
        quantumVolatilityFilter: true,
        quantumVolThreshold: 0.2,
        showLiquidationHeatmap: false,
        liquidationHeatmapIntensity: 1.0,
        liquidationShowBubbles: true,
        // Supertrend Defaults
        showSupertrend: true,
        supertrendAtrPeriod: 10,
        supertrendMultiplier: 3.0,
        supertrendChangeATR: true,
        supertrendShowSignals: true,
        supertrendHighlighting: true,
        // MSB-OB Defaults
        showMsbOb: false,
        msbObZigzagLen: 9,
        msbObFibFactor: 0.33,
        msbObShowZigzag: true,
        msbObDeleteBroken: true,
        showCandlestickPatterns: false,
        // ── Wick Rejection S/R Defaults ──
        showWickSR: false,
        wickSRTimeframe: '15m',
        wickSRLookback: 300,
        wickSRMinTouches: 25,
        wickSRAtrPeriod: 14,
        wickSRAtrMultiplier: 0.5,
        wickSRShowZones: true,
        wickSRShowLabels: true,
        showVWAPSD: false,
        vwapSDMultiplier1: 1.0,
        vwapSDMultiplier2: 2.0,
        vwapSDMultiplier3: 2.5,
        vwapAnchor: 'Session',
        // ── Aether Flow System ──
        showAetherFlow: false,
        aetherUtBot: true,
        aetherSupertrend: true,
        aetherSmc: true,
        aetherFvg: true,
    },
    setIndicatorSettings: (settings) => set({ indicatorSettings: settings }),
        }),
        {
            name: 'bot-store-storage',
        }
    )
);
