export const ALL_L2_FEATURES = [
    { internal: "Effective_Spread", name: "Effective Spread" },
    { internal: "Spread_ROC", name: "Spread ROC" },
    { internal: "Mid_Price_Acceleration", name: "Mid-Price Acceleration" },
    { internal: "Spread_Asymmetry", name: "Spread Asymmetry" },
    { internal: "WAP_Top_5", name: "WAP Top 5" },
    { internal: "WAP_Top_10", name: "WAP Top 10" },
    { internal: "Multi_Level_Imbalance_Top5", name: "Multi-Level Imbalance (Top 5)" },
    { internal: "Multi_Level_Imbalance_Top10", name: "Multi-Level Imbalance (Top 10)" },
    { internal: "Depth_Ratio", name: "Depth Ratio (Bid/Ask)" },
    { internal: "Ask_Wall_Distance", name: "Wall Distance (Ask)" },
    { internal: "Bid_Wall_Distance", name: "Wall Distance (Bid)" },
    { internal: "Order_Book_Skewness", name: "Order Book Skewness (Sk)" },
    { internal: "Level_1_Imbalance", name: "Level-1 Imbalance" },
    { internal: "Imbalance_Momentum", name: "Imbalance Momentum" },
    { internal: "Order_Flow_Imbalance", name: "Order Flow Imbalance (OFI)" },
    { internal: "CVD_Proxy", name: "Cumulative Volume Delta (CVD)" },
    { internal: "CVD_Acceleration", name: "CVD Acceleration" },
    { internal: "Realized_Micro_Volatility", name: "Realized Micro-Volatility" },
    { internal: "Tick_Test_Roll", name: "Tick Test Roll (Auto-correlation)" },
    { internal: "obi", name: "Order Book Imbalance (OBI)" },
    { internal: "spread", name: "Quoted Spread" },
    { internal: "microprice", name: "Micro-Price" },
    { internal: "obi_delta", name: "OBI Delta ✨ (NEW)", desc: "Rate of change of Order Book Imbalance" },
    { internal: "microprice_deviation", name: "Microprice Deviation ✨ (NEW)", desc: "Deviation of volume-weighted microprice from midprice" },
    { internal: "quote_stuffing_ratio", name: "Quote Stuffing Ratio ✨ (NEW)", desc: "Proxy for spam (rapid placement vs execution)" },
    { internal: "depth_variance", name: "Order Book Depth Variance ✨ (NEW)", desc: "Rolling variance of bid/ask depth at top levels" },
    { internal: "slippage_proxy", name: "Slippage Proxy ✨ (NEW)", desc: "Estimated cost of a simulated 10 units market order" },
    { internal: "spread_reversion_rate", name: "Spread Reversion Rate ✨ (NEW)", desc: "Speed at which a widened spread contracts" },
    { internal: "smart_money_divergence", name: "Smart Money Divergence ✨ (NEW)", desc: "Divergence between price momentum and depth momentum" },
    { internal: "bid_ask_absorption", name: "Bid/Ask Absorption Rate ✨ (NEW)", desc: "Rate at which limit orders are absorbing aggressive market flow" },
    { internal: "liquidity_replenishment_rate", name: "Liquidity Replenishment Rate ✨ (NEW)", desc: "Time-proxy for liquidity refilling after level clearance" },
    { internal: "bbo_flicker_rate", name: "BBO Flicker Rate ✨ (NEW)", desc: "Volatility of the top-of-book levels" },
    { internal: "order_flow_toxicity", name: "Order Flow Toxicity (VPIN) ✨ (NEW)", desc: "Probability of Informed Trading based on depth" },
    { internal: "hidden_volume_proxy", name: "Hidden Volume Proxy ✨ (NEW)", desc: "Detection of abnormally low slippage despite large volume" },
    
    // ── 🚀 30 NEW ADVANCED L2 METRICS ────────────────────────
    { internal: "ask_slope", name: "Ask Slope 🚀 ADVANCED", desc: "Gradient of ask liquidity density" },
    { internal: "bid_slope", name: "Bid Slope 🚀 ADVANCED", desc: "Gradient of bid liquidity density" },
    { internal: "book_convexity", name: "Book Convexity 🚀 ADVANCED", desc: "Second derivative of liquidity shape" },
    { internal: "book_concavity", name: "Book Concavity 🚀 ADVANCED", desc: "Hollowness of the order book" },
    { internal: "cancel_replace_ratio", name: "Cancel-Replace Ratio 🚀 ADVANCED", desc: "Ratio of canceled to replaced limit orders" },
    { internal: "top_order_resting_time", name: "Top Order Resting Time 🚀 ADVANCED", desc: "Average time orders sit at BBO" },
    { internal: "spontaneous_quote_shift", name: "Spontaneous Quote Shift 🚀 ADVANCED", desc: "Price shift without executed volume" },
    { internal: "order_book_entropy", name: "Order Book Entropy 🚀 ADVANCED", desc: "Information entropy of depth distribution" },
    { internal: "quote_flicker_ratio", name: "Quote Flicker Ratio 🚀 ADVANCED", desc: "High-frequency quote updates at BBO" },
    { internal: "microprice_jumps", name: "Microprice Jumps 🚀 ADVANCED", desc: "Frequency of discontinuous microprice moves" },
    { internal: "volume_weighted_spread", name: "Volume Weighted Spread 🚀 ADVANCED", desc: "Spread scaled by cumulative volume" },
    { internal: "limit_order_depletion_rate", name: "Order Depletion Rate 🚀 ADVANCED", desc: "Speed of liquidity consumption at top levels" },
    { internal: "liquidity_mirage_ratio", name: "Liquidity Mirage Ratio 🚀 ADVANCED", desc: "Ratio of fleeting vs resting liquidity" },
    { internal: "depth_ratio_top_5", name: "Depth Ratio Top 5 🚀 ADVANCED", desc: "Bid/Ask volume ratio within 5 levels" },
    { internal: "depth_ratio_top_10", name: "Depth Ratio Top 10 🚀 ADVANCED", desc: "Bid/Ask volume ratio within 10 levels" },
    { internal: "imbalance_variance", name: "Imbalance Variance 🚀 ADVANCED", desc: "Rolling variance of order book imbalance" },
    { internal: "level_by_level_pressure", name: "Level-by-level Pressure 🚀 ADVANCED", desc: "Micro-pressure applied by individual levels" },
    { internal: "order_book_decay", name: "Order Book Decay 🚀 ADVANCED", desc: "Exponential decay of depth away from mid" },
    { internal: "quote_volatility", name: "Quote Volatility 🚀 ADVANCED", desc: "Standard deviation of BBO updates" },
    { internal: "order_arrival_intensity", name: "Order Arrival Intensity 🚀 ADVANCED", desc: "Poisson intensity of new limit orders" },
    { internal: "book_resiliency", name: "Book Resiliency 🚀 ADVANCED", desc: "Recovery speed of L2 shape post-shock" },
    { internal: "bid_ask_covariance", name: "Bid-Ask Covariance 🚀 ADVANCED", desc: "Covariance between bid and ask depths" },
    { internal: "spoofing_imbalance_ratio", name: "Spoofing Imbalance Ratio 🚀 ADVANCED", desc: "Imbalance adjusted for likely spoofed size" },
    { internal: "tick_size_dependency", name: "Tick Size Dependency 🚀 ADVANCED", desc: "Spread expressed in minimum tick multiples" },
    { internal: "iceberg_revelation_rate", name: "Iceberg Revelation Rate 🚀 ADVANCED", desc: "Rate at which hidden volume is exposed at BBO" },
    { internal: "l2_relative_strength", name: "L2 Relative Strength 🚀 ADVANCED", desc: "Momentum indicator applied to L2 depth" },
    { internal: "bid_wall_absorption", name: "Bid Wall Absorption 🚀 ADVANCED", desc: "Execution rate into a large bid cluster" },
    { internal: "ask_wall_absorption", name: "Ask Wall Absorption 🚀 ADVANCED", desc: "Execution rate into a large ask cluster" },
    { internal: "l2_liquidity_vacuum", name: "Liquidity Vacuum 🚀 ADVANCED", desc: "Sudden withdrawal of liquidity leading to air pockets" },
    { internal: "cross_spread_momentum", name: "Cross-Spread Momentum 🚀 ADVANCED", desc: "Momentum of mid-price across the bid-ask bounce" }
];

export const BASIC_L2_INTERNAL_NAMES = [
    "obi", "spread", "microprice", "Imbalance_Momentum", "Depth_Ratio", 
    "CVD_Proxy", "Multi_Level_Imbalance_Top5", "OFI_Acceleration", "Level_1_Imbalance"
];

export const BASIC_L2_FEATURES = ALL_L2_FEATURES.filter(f => BASIC_L2_INTERNAL_NAMES.includes(f.internal));
export const ADV_L2_FEATURES = ALL_L2_FEATURES.filter(f => !BASIC_L2_INTERNAL_NAMES.includes(f.internal));

export const ALL_TRADE_FEATURES = [
    { internal: "cvd", name: "Cumulative Volume Delta (CVD)" },
    { internal: "buy_volume", name: "Buy Volume Profile" },
    { internal: "sell_volume", name: "Sell Volume Profile" },
    { internal: "trade_count", name: "Trade Count (Tick Velocity)" },
    { internal: "rolling_vol_imbalance", name: "Rolling Volume Imbalance ✨ (NEW)", desc: "Buy vs Sell dominance (100 ticks)" },
    { internal: "trade_velocity", name: "Trade Velocity (Hz) ✨ (NEW)", desc: "Trades executed per second" },
    { internal: "vwap_deviation", name: "VWAP Deviation", desc: "Distance of current price from rolling VWAP" },
    { internal: "consecutive_runs", name: "Consecutive Runs ✨ (NEW)", desc: "Streak length of trades in the same direction" },
    { internal: "aggressor_ratio", name: "Aggressor Ratio", desc: "Percentage of trades initiated by buyers" },
    { internal: "avg_trade_size", name: "Average Trade Size (ATS) ✨ (NEW)", desc: "Mean size of last 100 trades" },
    { internal: "whale_trade_freq", name: "Whale Trade Frequency 🐋 ✨ (NEW)", desc: "Frequency of trades > 95th percentile" },
    { internal: "retail_participation_ratio", name: "Retail Participation ✨ (NEW)", desc: "Frequency of trades < 25th percentile" },
    { internal: "trade_size_variance", name: "Trade Size Variance ✨ (NEW)", desc: "Volatility in order flow sizes" },
    { internal: "iceberg_proxy_count", name: "Iceberg Order Proxy 🧊 ✨ (NEW)", desc: "Consecutive trades executed exactly at same price" },
    { internal: "up_down_tick_ratio", name: "Up/Down Tick Volume Ratio ✨ (NEW)", desc: "Volume traded on up-ticks vs down-ticks" },
    { internal: "micro_volatility", name: "Micro-Volatility ✨ (NEW)", desc: "Standard deviation of tick returns" },
    { internal: "amihud_illiquidity", name: "Amihud Illiquidity ✨ (NEW)", desc: "Price impact per unit volume traded" },
    { internal: "tick_speed", name: "Tick Speed (ms)", desc: "Average milliseconds between trades" },
    { internal: "tick_acceleration", name: "Tick Acceleration ✨ (NEW)", desc: "Rate of change of tick speed (Momentum of momentum)" },
    { internal: "zero_tick_ratio", name: "Zero-Tick Ratio ✨ (NEW)", desc: "Percentage of trades causing zero price movement" },
    { internal: "realized_variance", name: "Realized Variance ✨ (NEW)", desc: "Sum of squared tick returns" },
    { internal: "kyles_lambda", name: "Kyle's Lambda ✨ (NEW)", desc: "Regression slope of price change on volume (Market impact)" },
    { internal: "autocorr_signs", name: "Order Sign Auto-correlation ✨ (NEW)", desc: "Predictability of order direction (Lag-1)" },
    { internal: "entropy_of_signs", name: "Order Flow Entropy ✨ (NEW)", desc: "Shannon entropy of trade directions (Predictability)" },
    { internal: "roll_measure_spread", name: "Roll Measure Spread ✨ (NEW)", desc: "Implicit spread estimated from tick covariance" },
    { internal: "vpin_proxy", name: "VPIN Proxy ✨ (NEW)", desc: "Volume-Synchronized Probability of Informed Trading" }
];

// ── Hybrid Deep: Trade Tick Features ────────────────────────────────────
export const ALL_HYBRID_DEEP_TRADE_FEATURES = [
    { internal: "cvd",                   name: "CVD (Real aggTrade)",             desc: "Cumulative Volume Delta from actual executed trades" },
    { internal: "buy_volume",            name: "Buy Volume",                       desc: "Aggressive buy volume per tick" },
    { internal: "sell_volume",           name: "Sell Volume",                      desc: "Aggressive sell volume per tick" },
    { internal: "trade_count",           name: "Trade Count",                      desc: "Number of trades (tick velocity)" },
    { internal: "rolling_vol_imbalance", name: "Rolling Volume Imbalance ✨ (NEW)", desc: "Buy vs Sell dominance (100 ticks)" },
    { internal: "trade_velocity", name: "Trade Velocity (Hz) ✨ (NEW)", desc: "Trades executed per second" },
    { internal: "vwap_deviation",        name: "VWAP Deviation",                   desc: "Price distance from running VWAP" },
    { internal: "consecutive_runs", name: "Consecutive Runs ✨ (NEW)", desc: "Streak length of trades in the same direction" },
    { internal: "aggressor_ratio",       name: "Aggressor Ratio",                  desc: "Rolling buy aggressor rate (100-tick window)" },
    { internal: "avg_trade_size", name: "Average Trade Size (ATS) ✨ (NEW)", desc: "Mean size of last 100 trades" },
    { internal: "whale_trade_freq", name: "Whale Trade Frequency 🐋 ✨ (NEW)", desc: "Frequency of trades > 95th percentile" },
    { internal: "retail_participation_ratio", name: "Retail Participation ✨ (NEW)", desc: "Frequency of trades < 25th percentile" },
    { internal: "trade_size_variance", name: "Trade Size Variance ✨ (NEW)", desc: "Volatility in order flow sizes" },
    { internal: "iceberg_proxy_count", name: "Iceberg Order Proxy 🧊 ✨ (NEW)", desc: "Consecutive trades executed exactly at same price" },
    { internal: "up_down_tick_ratio", name: "Up/Down Tick Volume Ratio ✨ (NEW)", desc: "Volume traded on up-ticks vs down-ticks" },
    { internal: "micro_volatility", name: "Micro-Volatility ✨ (NEW)", desc: "Standard deviation of tick returns" },
    { internal: "amihud_illiquidity", name: "Amihud Illiquidity ✨ (NEW)", desc: "Price impact per unit volume traded" },
    { internal: "tick_speed",            name: "Tick Speed (ms/trade)",            desc: "Average milliseconds between consecutive trades" },
    { internal: "tick_acceleration", name: "Tick Acceleration ✨ (NEW)", desc: "Rate of change of tick speed" },
    { internal: "zero_tick_ratio", name: "Zero-Tick Ratio ✨ (NEW)", desc: "Percentage of trades causing zero price movement" },
    { internal: "realized_variance", name: "Realized Variance ✨ (NEW)", desc: "Sum of squared tick returns" },
    { internal: "kyles_lambda", name: "Kyle's Lambda ✨ (NEW)", desc: "Regression slope of price change on volume (Market impact)" },
    { internal: "autocorr_signs", name: "Order Sign Auto-correlation ✨ (NEW)", desc: "Predictability of order direction (Lag-1)" },
    { internal: "entropy_of_signs", name: "Order Flow Entropy ✨ (NEW)", desc: "Shannon entropy of trade directions (Predictability)" },
    { internal: "roll_measure_spread", name: "Roll Measure Spread ✨ (NEW)", desc: "Implicit spread estimated from tick covariance" },
    { internal: "vpin_proxy", name: "VPIN Proxy ✨ (NEW)", desc: "Volume-Synchronized Probability of Informed Trading" },
    
    // ── 🚀 30 NEW CROSS-DOMAIN METRICS ────────────────────────
    { internal: "trade_impact_top_5_levels", name: "Trade Impact Top 5 🚀 CROSS-DOMAIN", desc: "L2 levels depleted per standard trade size" },
    { internal: "slippage_vs_expected_l2", name: "Slippage vs Expected 🚀 CROSS-DOMAIN", desc: "Actual execution slippage vs L2 theoretical" },
    { internal: "price_impact_asymmetry", name: "Price Impact Asymmetry 🚀 CROSS-DOMAIN", desc: "Difference in impact between buy vs sell trades" },
    { internal: "vpin_by_trade_size", name: "VPIN by Trade Size 🚀 CROSS-DOMAIN", desc: "Volume PIN weighted by individual trade sizes" },
    { internal: "order_flow_toxicity_per_level", name: "Toxicity per L2 Level 🚀 CROSS-DOMAIN", desc: "Toxicity metric distributed across L2 depth" },
    { internal: "sweep_to_fill_ratio", name: "Sweep-to-Fill Ratio 🚀 CROSS-DOMAIN", desc: "Ratio of market sweeps to passive fills" },
    { internal: "aggressor_sequence_pattern", name: "Aggressor Sequence Pattern 🚀 CROSS-DOMAIN", desc: "Markov transition probabilities of aggressors" },
    { internal: "block_trade_ratio_vs_depth", name: "Block Trade vs Depth 🚀 CROSS-DOMAIN", desc: "Block volume relative to L2 total depth" },
    { internal: "hawkes_intensity_jump", name: "Hawkes Intensity Jump 🚀 CROSS-DOMAIN", desc: "Jump intensity of Hawkes trade clustering" },
    { internal: "trade_herfindahl_hirschman_index", name: "Trade HHI Concentration 🚀 CROSS-DOMAIN", desc: "HHI of trade size concentration" },
    { internal: "vwap_microprice_divergence", name: "VWAP-Microprice Div 🚀 CROSS-DOMAIN", desc: "Divergence between Trade VWAP and L2 Microprice" },
    { internal: "twap_l2_mid_divergence", name: "TWAP-L2 Mid Div 🚀 CROSS-DOMAIN", desc: "Divergence between TWAP and L2 Mid-Price" },
    { internal: "dark_pool_lit_proxy", name: "Dark Pool Lit Proxy 🚀 CROSS-DOMAIN", desc: "Unexplained volume vs visible L2 quote updates" },
    { internal: "liquidity_absorption_rate", name: "Liquidity Absorption Rate 🚀 CROSS-DOMAIN", desc: "Percentage of top-of-book L2 liquidity consumed" },
    { internal: "order_book_replenishment", name: "L2 Replenishment Speed 🚀 CROSS-DOMAIN", desc: "Time taken for limit orders to refill post-trade" },
    { internal: "smart_money_divergence_cross", name: "Smart Money Div (Cross) 🚀 CROSS-DOMAIN", desc: "Divergence between Trade CVD and OBI" },
    { internal: "pre_trade_cancel_ratio", name: "Pre-Trade Cancel Ratio 🚀 CROSS-DOMAIN", desc: "Ratio of limit orders canceled just before a trade" },
    { internal: "aggressive_trade_impact_atif", name: "Aggressive Impact (ATIF) 🚀 CROSS-DOMAIN", desc: "Number of L2 price levels penetrated by trade" },
    { internal: "hawkes_process_intensity", name: "Hawkes Vol Delta 🚀 CROSS-DOMAIN", desc: "Time-decayed exponential volume delta" },
    { internal: "hidden_iceberg_execution", name: "Hidden Iceberg Execution 🚀 CROSS-DOMAIN", desc: "Volume executed inside spread without L2 visibility" },
    { internal: "tick_arrival_clustering", name: "Tick Arrival Clustering 🚀 CROSS-DOMAIN", desc: "Density of trades arriving in millisecond clusters" },
    { internal: "fill_rate_vs_cancel_rate", name: "Fill vs Cancel Rate 🚀 CROSS-DOMAIN", desc: "Ratio of successful fills to L2 cancellations" },
    { internal: "trade_to_quote_ratio", name: "Trade-to-Quote Ratio 🚀 CROSS-DOMAIN", desc: "Number of trades per L2 quote update" },
    { internal: "limit_order_survival_prob", name: "Survival Probability 🚀 CROSS-DOMAIN", desc: "Probability a limit order survives next 10 trades" },
    { internal: "informed_trading_proxy", name: "Informed Trading Proxy 🚀 CROSS-DOMAIN", desc: "Proxy for institutional informed trading flow" },
    { internal: "market_maker_inventory_stress", name: "MM Inventory Stress 🚀 CROSS-DOMAIN", desc: "Estimate of Market Maker directional exposure" },
    { internal: "cross_domain_momentum_ignition", name: "Momentum Ignition 🚀 CROSS-DOMAIN", desc: "Cross-domain flag for momentum ignition spoofing" },
    { internal: "l2_depth_vs_trade_vol_ratio", name: "Depth vs Volume Ratio 🚀 CROSS-DOMAIN", desc: "Total L2 depth divided by 1m rolling trade volume" },
    { internal: "effective_spread_realization", name: "Spread Realization 🚀 CROSS-DOMAIN", desc: "Actual spread realized on executions vs quoted" },
    { internal: "quote_depletion_vs_trade_intensity", name: "Quote Depletion Intensity 🚀 CROSS-DOMAIN", desc: "Pace of quote pulling vs trade arrivals" }
];


// ── Predatory Liquidity Pipeline (PLP) Modules ────────────────────────
export const PLP_MODULES = [
    {
        id: 'liquidity_cluster',
        name: 'Liquidity Cluster & Density Module',
        desc: 'Maps retail trapped funds and liquidation zones.',
        icon: 'Target',
        color: 'rose',
        features: [
            { id: 'abs_long_liq_pool', name: 'Absolute Long Liquidation Pool', mandatory: true },
            { id: 'abs_short_liq_pool', name: 'Absolute Short Liquidation Pool', mandatory: true },
            { id: 'liquidation_density_z_score', name: 'Liquidation Density Z-Score' },
            { id: 'leverage_washout_z_score', name: 'Leverage Washout Z-Score' },
            { id: 'high_leverage_cluster_proximity', name: 'High-Leverage Cluster Proximity' },
            { id: 'margin_call_proximity_index', name: 'Margin Call Proximity Index' },
            { id: 'magnetic_liquidity_pull_vector', name: 'Magnetic Liquidity Pull Vector' },
            { id: 'liq_cluster_density_heatmap', name: 'Liquidation Cluster Density Heatmap' },
            { id: 'synthetic_leverage_ratio', name: 'Synthetic Leverage Ratio' },
            { id: 'hidden_liquidity_absorption', name: 'Hidden Liquidity Absorption' },
            { id: 'stale_liquidity_decay', name: 'Stale Liquidity Decay' },
            { id: 'cross_margin_cascade_risk', name: 'Cross-Margin Cascade Risk' },
            // 🚀 NEW 
            { id: 'stealth_liquidation_proxies', name: 'Stealth Liquidation Proxies 🚀 PLP' },
            { id: 'gamma_exposure_imbalance', name: 'GEX Imbalance 🚀 PLP' },
            { id: 'zero_dte_options_proxy_pull', name: '0-DTE Options Pull Proxy 🚀 PLP' },
            { id: 'retail_pain_threshold', name: 'Retail Pain Threshold 🚀 PLP' },
            { id: 'liquidation_void_zones', name: 'Liquidation Void Zones 🚀 PLP' },
            { id: 'smart_money_trap_indicator', name: 'Smart Money Trap 🚀 PLP' },
            { id: 'leveraged_retail_skew', name: 'Leveraged Retail Skew 🚀 PLP' }
        ]
    },
    {
        id: 'cascade_dynamics',
        name: 'Cascade & Trigger Dynamics Module',
        desc: 'Measures domino effects and chain reactions of liquidations.',
        icon: 'Zap',
        color: 'orange',
        features: [
            { id: 'liquidation_cascade_multiplier', name: 'Liquidation Cascade Multiplier' },
            { id: 'long_squeeze_probability', name: 'Long Squeeze Probability' },
            { id: 'short_squeeze_probability', name: 'Short Squeeze Probability' },
            { id: 'cascade_velocity_index', name: 'Cascade Velocity Index' },
            { id: 'domino_effect_threshold', name: 'Domino Effect Threshold' },
            { id: 'cascade_decay_rate', name: 'Cascade Decay Rate' },
            { id: 'forced_liquidation_trigger_pts', name: 'Forced Liquidation Trigger Points' },
            { id: 'volatility_expansion_on_liq', name: 'Volatility Expansion on Liquidation' },
            { id: 'squeeze_exhaustion_metric', name: 'Squeeze Exhaustion Metric' },
            { id: 'liquidator_bot_activity_proxy', name: 'Liquidator Bot Activity Proxy' },
            // 🚀 NEW
            { id: 'domino_trigger_threshold_alpha', name: 'Domino Trigger Alpha 🚀 PLP' },
            { id: 'contagion_effect_probability', name: 'Contagion Effect Prob 🚀 PLP' },
            { id: 'price_volume_dislocation_liq', name: 'Price-Volume Dislocation 🚀 PLP' },
            { id: 'cascade_halflife_decay', name: 'Cascade Half-life Decay 🚀 PLP' },
            { id: 'liquidation_wall_impact', name: 'Liquidation Wall Impact 🚀 PLP' },
            { id: 'short_squeeze_velocity_factor', name: 'Short Squeeze Velocity Factor 🚀 PLP' },
            { id: 'synthetic_domino_proxy', name: 'Synthetic Domino Proxy 🚀 PLP' }
        ]
    },
    {
        id: 'stop_hunt',
        name: 'Stop-Hunt & Sweep Mechanism Module',
        desc: 'Identifies retail stop-loss hunts and fakeout vectors.',
        icon: 'Crosshair',
        color: 'red',
        features: [
            { id: 'stop_hunt_probability', name: 'Stop-Hunt Probability' },
            { id: 'liquidity_sweep_velocity', name: 'Liquidity Sweep Velocity' },
            { id: 'fakeout_prob_model', name: 'Fakeout Probability Model (FPM)', mandatory: true },
            { id: 'sweep_and_reversal_ratio', name: 'Sweep and Reversal Ratio' },
            { id: 'stop_loss_trigger_density', name: 'Stop-Loss Trigger Density' },
            { id: 'predatory_algo_footprint', name: 'Predatory Algo Footprint' },
            { id: 'institutional_sweep_divergence', name: 'Institutional Sweep Divergence' },
            { id: 'retail_trap_indicator', name: 'Retail Trap Indicator' },
            { id: 'high_frequency_hunt_ratio', name: 'High Frequency Hunt Ratio' },
            { id: 'sweep_efficiency_score', name: 'Sweep Efficiency Score' },
            // 🚀 NEW
            { id: 'low_latency_sweep_detection', name: 'Low-Latency Sweep Detect 🚀 PLP' },
            { id: 'wash_trade_sweep_detection', name: 'Wash Trade Sweep Detect 🚀 PLP' },
            { id: 'institutional_footprint_masking', name: 'Institutional Masking 🚀 PLP' },
            { id: 'fakeout_velocity_acceleration', name: 'Fakeout Velocity Accel 🚀 PLP' },
            { id: 'stop_hunt_asymmetry', name: 'Stop-Hunt Asymmetry 🚀 PLP' },
            { id: 'retail_panic_sweep_proxy', name: 'Retail Panic Sweep Proxy 🚀 PLP' },
            { id: 'algo_hunt_intensity', name: 'Algo Hunt Intensity 🚀 PLP' }
        ]
    },
    {
        id: 'smc_orderflow',
        name: 'SMC & Order Flow Matrix Module',
        desc: 'Confluence between Smart Money Concepts and live order flow.',
        icon: 'Activity',
        color: 'purple',
        features: [
            { id: 'institutional_order_flow_imbalance', name: 'Institutional Order Flow Imbalance' },
            { id: 'smart_money_accumulation_dist', name: 'Smart Money Accumulation/Distribution' },
            { id: 'fvg_liquidity_draw_prob', name: 'FVG Liquidity Draw Probability' },
            { id: 'order_block_mitigation_speed', name: 'Order Block Mitigation Speed' },
            { id: 'time_weighted_vampire_flow', name: 'Time-Weighted Vampire Flow' },
            { id: 'bms_confirmation_strength', name: 'BMS Confirmation Strength' },
            { id: 'choch_volatility_multiplier', name: 'CHoCH Volatility Multiplier' },
            { id: 'imbalance_to_volume_ratio', name: 'Imbalance to Volume Ratio' },
            { id: 'sponsor_candle_footprint', name: 'Sponsor Candle Footprint' },
            { id: 'dark_pool_proxy_index', name: 'Dark Pool Proxy Index' },
            // 🚀 NEW
            { id: 'fvg_exhaustion_rate', name: 'FVG Exhaustion Rate 🚀 PLP' },
            { id: 'order_block_defense_strength', name: 'Order Block Defense 🚀 PLP' },
            { id: 'bos_momentum_velocity', name: 'BoS Momentum Velocity 🚀 PLP' },
            { id: 'liquidity_void_replenishment', name: 'Void Replenishment 🚀 PLP' },
            { id: 'premium_discount_imbalance', name: 'Premium/Discount Imbalance 🚀 PLP' },
            { id: 'smart_money_reversal_divergence', name: 'Smart Money Reversal Div 🚀 PLP' },
            { id: 'institutional_candle_dominance', name: 'Institutional Candle Dominance 🚀 PLP' }
        ]
    },
    {
        id: 'ict_macro_concepts',
        name: 'ICT Time & Macro Dynamics Module',
        desc: 'Advanced ICT concepts based on precise UTC Time & Macro Sweeps.',
        icon: 'Clock',
        color: 'emerald',
        features: [
            { id: 'london_killzone_momentum', name: 'London Killzone Momentum' },
            { id: 'ny_killzone_momentum', name: 'New York Killzone Momentum' },
            { id: 'asian_consolidation_breakout', name: 'Asian Consolidation Breakout' },
            { id: 'true_day_open_deviation', name: 'True Day Open Deviation' },
            { id: 'pdh_pdl_sweep_proxy', name: 'PDH/PDL Sweep Proxy' },
            { id: 'smt_divergence_synthetic', name: 'SMT Divergence (Synthetic)' },
            { id: 'institutional_pricing_magnet', name: 'Institutional Pricing Magnet' },
            { id: 'judas_swing_probability', name: 'Judas Swing Probability' },
            { id: 'silver_bullet_time_proximity', name: 'Silver Bullet Proximity' },
            { id: 'turtle_soup_fakeout', name: 'Turtle Soup Fakeout' }
        ]
    },
    {
        id: 'candlestick_psychology',
        name: 'Candlestick Morphology & Psychology Module',
        desc: 'Advanced shape, conviction, and trap metrics mapped to math matrices.',
        icon: 'CandlestickChart',
        color: 'yellow',
        features: [
            { id: 'lower_wick_absorption_ratio', name: 'Lower Wick Absorption Ratio' },
            { id: 'upper_wick_distribution_proxy', name: 'Upper Wick Distribution Proxy' },
            { id: 'wick_to_wick_asymmetry', name: 'Wick-to-Wick Asymmetry (WWA)' },
            { id: 'tweezer_alignment_proxy', name: 'Tweezer Alignment Proxy' },
            { id: 'body_to_spread_ratio', name: 'Body-to-Spread Ratio (Doji-Marubozu)' },
            { id: 'real_body_shift_rate', name: 'Real Body Shift Rate' },
            { id: 'volatility_contraction_index', name: 'Volatility Contraction Index (Inside Bars)' },
            { id: 'micro_gap_velocity', name: 'Micro-Gap Velocity' },
            { id: 'climax_volume_reversal', name: 'Climax Volume Reversal Index' },
            { id: 'effort_vs_result_divergence', name: 'Effort vs Result Divergence (Wyckoff)' },
            { id: 'volume_profile_shift', name: 'Volume Profile Shift in Body' },
            { id: 'engulfing_momentum_float', name: 'Engulfing Momentum Float' },
            { id: 'morning_star_probability', name: 'Morning/Evening Star Probability' },
            { id: 'fomo_intensity_index', name: 'FOMO Intensity Index (3 Soldiers/Crows)' },
            { id: 'harami_squeeze_breakout', name: 'Harami (Inside Bar) Squeeze Breakout' },
            { id: 'candle_creation_velocity', name: 'Candle Creation Velocity' },
            { id: 'intra_candle_trend', name: 'Intra-Candle Micro Trend' },
            { id: 'last_second_spike_ratio', name: 'Last Second Spike Ratio' },
            { id: 'candle_center_of_gravity', name: 'Candle Center of Gravity (COG)' },
            { id: 'shadow_overlap_ratio', name: 'Shadow Overlap Ratio' },
            { id: 'fractal_wick_divergence', name: 'Fractal Wick Divergence' },
            { id: 'intra_candle_delta_shift', name: 'Intra-Candle Delta Shift' },
            { id: 'trade_velocity_skewness', name: 'Trade Velocity Skewness' },
            { id: 'tick_density_ratio', name: 'Tick-Density Ratio (Wick vs Body)' },
            { id: 'time_at_extremes', name: 'Time-at-Extremes (TaE)' },
            { id: 'runaway_gap_probability', name: 'Runaway Gap Probability' },
            { id: 'shooting_star_composite', name: 'Hanging Man / Shooting Star Composite' },
            { id: 'mean_reversion_stretch', name: 'Mean Reversion Stretch Index' },
            { id: 'shadow_box_imbalance', name: 'Shadow Box Imbalance' },
            { id: 'sequential_body_compression', name: 'Sequential Body Compression' }
        ]
    },
    {
        id: 'market_structure_swing',
        name: 'Market Structure & Swing Dynamics',
        desc: 'Advanced metrics based on Swing Highs/Lows and Liquidity Pools using HFT Timeframe logic.',
        icon: 'Activity',
        color: 'purple',
        features: [
            { id: 'swing_failure_pattern_proxy', name: 'Swing Failure Pattern (SFP) Proxy' },
            { id: 'break_of_structure_velocity', name: 'BOS (Break of Structure) Velocity' },
            { id: 'change_of_character_trigger', name: 'ChoCh (Change of Character) Trigger' },
            { id: 'equal_highs_lows_pool', name: 'Equal Highs / Lows (Liquidity Pool)' },
            { id: 'distance_to_liquidity_pool', name: 'Distance to Nearest Liquidity Pool' },
            { id: 'swing_leg_amplitude', name: 'Swing Leg Amplitude (Expansion)' },
            { id: 'time_since_last_swing', name: 'Time Since Last Major Swing (Exhaustion)' },
            { id: 'swing_leg_velocity', name: 'Swing Leg Velocity (Aggression Ratio)' },
            { id: 'premium_discount_matrix', name: 'Premium vs Discount Matrix (Fib 0.5)' },
            { id: 'fractal_density_index', name: 'Fractal Density Index' }
        ]
    },
    {
        id: 'margin_risk',
        name: 'Margin, Volatility & Risk Evaluation Module',
        desc: 'Quantifies leverage risk, panic selling, and volatility shifts.',
        icon: 'ShieldAlert',
        color: 'pink',
        features: [
            { id: 'oi_wipeout_ratio', name: 'Open Interest Wipeout Ratio', mandatory: true },
            { id: 'funding_rate_shift', name: 'Funding Rate Shift', mandatory: true },
            { id: 'funding_rate_shift_pre_liq', name: 'Funding Rate Shift Pre-Liquidation' },
            { id: 'implied_margin_pressure', name: 'Implied Margin Pressure' },
            { id: 'vol_skew_liquidation_bias', name: 'Vol Skew Liquidation Bias' },
            { id: 'bid_ask_spread_blowout', name: 'Bid-Ask Spread Blowout' },
            { id: 'flash_crash_probability', name: 'Flash Crash Probability' },
            { id: 'tail_risk_expansion_index', name: 'Tail Risk Expansion Index' },
            { id: 'gamma_squeeze_synthetic', name: 'Gamma Squeeze (Synthetic)' },
            { id: 'leverage_decay_factor', name: 'Leverage Decay Factor' },
            { id: 'margin_variance_premium', name: 'Margin Variance Premium' },
            // 🚀 NEW
            { id: 'cross_exchange_basis_blowout', name: 'Basis Blowout 🚀 PLP' },
            { id: 'perpetual_premium_squeeze', name: 'Perp Premium Squeeze 🚀 PLP' },
            { id: 'margin_call_chain_reaction', name: 'Margin Chain Reaction 🚀 PLP' },
            { id: 'volatility_smile_skewness', name: 'Volatility Smile Skewness 🚀 PLP' },
            { id: 'panic_selling_intensity', name: 'Panic Selling Intensity 🚀 PLP' },
            { id: 'tail_risk_contagion_factor', name: 'Tail Risk Contagion Factor 🚀 PLP' }
        ]
    },
    {
        id: 'market_manipulation',
        name: 'Market Manipulation & HFT Proxies',
        desc: 'Advanced detection of spoofing, layering, and wash trading.',
        icon: 'Search',
        color: 'cyan',
        features: [
            { id: 'spoofing_flag', name: 'Spoofing Detection Flag ✨ (NEW)' },
            { id: 'layering_density', name: 'Layering Density ✨ (NEW)' },
            { id: 'liquidity_mirage', name: 'Liquidity Mirage Index ✨ (NEW)' },
            { id: 'wash_trading_prob', name: 'Wash Trading Probability ✨ (NEW)' },
            { id: 'stop_hunting_prob', name: 'Stop-Hunting Probability ✨ (NEW)' },
            { id: 'hft_front_running', name: 'HFT Front-Running Proxy ✨ (NEW)' },
            { id: 'momentum_ignition', name: 'Momentum Ignition ✨ (NEW)' },
            // 🚀 NEW
            { id: 'quote_stuffing_index_hft', name: 'Quote Stuffing Index 🚀 PLP' },
            { id: 'ping_pong_trade_detection', name: 'Ping-Pong Trade Detect 🚀 PLP' },
            { id: 'sub_millisecond_spoofing_alpha', name: 'Sub-ms Spoofing Alpha 🚀 PLP' },
            { id: 'layering_cancellation_velocity', name: 'Layering Cancel Velocity 🚀 PLP' },
            { id: 'order_book_ghosting_ratio', name: 'Order Book Ghosting Ratio 🚀 PLP' },
            { id: 'hft_latency_arbitrage_proxy', name: 'HFT Latency Arb Proxy 🚀 PLP' }
        ]
    }
];
