"""Add broadcast_live_logs to NotificationSettings

Revision ID: 06c3c6be3bf3
Revises: b90b8bdf8159
Create Date: 2026-04-02 20:41:49.663994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c3c6be3bf3'
down_revision: Union[str, Sequence[str], None] = 'b90b8bdf8159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_settings', sa.Column('broadcast_live_logs', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_settings', 'broadcast_live_logs')
    # ### end Alembic commands ###
