"""Add model training jobs

Revision ID: 09d8b8bed6b3
Revises: a2313e5a46fd
Create Date: 2026-05-02 09:51:48.470957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d8b8bed6b3'
down_revision: Union[str, Sequence[str], None] = 'a2313e5a46fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_training_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='trainingstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('output_model_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['output_model_id'], ['custom_ml_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_training_jobs_id'), 'model_training_jobs', ['id'], unique=False)
    op.create_foreign_key('fk_active_version_id', 'custom_ml_models', 'model_versions', ['active_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_active_version_id', 'custom_ml_models', type_='foreignkey')
    op.drop_index(op.f('ix_model_training_jobs_id'), table_name='model_training_jobs')
    op.drop_table('model_training_jobs')
    # ### end Alembic commands ###
