"""Add LeadLagBot models

Revision ID: 0d45fc594824
Revises: 2425e74621f6
Create Date: 2026-03-04 10:11:12.269532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d45fc594824'
down_revision: Union[str, Sequence[str], None] = '2425e74621f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_lag_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('leader_pair', sa.String(), nullable=False),
    sa.Column('target_pair', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('trade_size', sa.Float(), nullable=False),
    sa.Column('take_profit_pct', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_paper_trading', sa.Boolean(), nullable=True),
    sa.Column('paper_balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_reason', sa.String(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_lag_bots_id'), 'lead_lag_bots', ['id'], unique=False)
    op.create_index(op.f('ix_lead_lag_bots_is_paper_trading'), 'lead_lag_bots', ['is_paper_trading'], unique=False)
    op.create_table('lead_lag_trade_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('trigger_reason', sa.String(), nullable=False),
    sa.Column('executed_pair', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['lead_lag_bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_lag_trade_logs_id'), 'lead_lag_trade_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_lag_trade_logs_id'), table_name='lead_lag_trade_logs')
    op.drop_table('lead_lag_trade_logs')
    op.drop_index(op.f('ix_lead_lag_bots_is_paper_trading'), table_name='lead_lag_bots')
    op.drop_index(op.f('ix_lead_lag_bots_id'), table_name='lead_lag_bots')
    op.drop_table('lead_lag_bots')
    # ### end Alembic commands ###
