"""Add auto_retrain and L2 features

Revision ID: 1092cad39267
Revises: 09d8b8bed6b3
Create Date: 2026-05-02 15:35:11.346864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1092cad39267'
down_revision: Union[str, Sequence[str], None] = '09d8b8bed6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_ml_models', sa.Column('is_auto_retrain', sa.Integer(), nullable=True))
    op.add_column('custom_ml_models', sa.Column('retrain_interval_hours', sa.Integer(), nullable=True))
    op.add_column('orderbook_snapshots', sa.Column('obi', sa.Float(), nullable=True))
    op.add_column('orderbook_snapshots', sa.Column('spread', sa.Float(), nullable=True))
    op.add_column('orderbook_snapshots', sa.Column('microprice', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderbook_snapshots', 'microprice')
    op.drop_column('orderbook_snapshots', 'spread')
    op.drop_column('orderbook_snapshots', 'obi')
    op.drop_column('custom_ml_models', 'retrain_interval_hours')
    op.drop_column('custom_ml_models', 'is_auto_retrain')
    # ### end Alembic commands ###
