"""Add market_type

Revision ID: 14e5d2bfe6f6
Revises: 311973220153
Create Date: 2026-07-11 17:33:42.620627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e5d2bfe6f6'
down_revision: Union[str, Sequence[str], None] = '311973220153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_ml_models', sa.Column('market_type', sa.String(), nullable=False, server_default='crypto'))
    op.add_column('model_training_jobs', sa.Column('market_type', sa.String(), nullable=False, server_default='crypto'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_training_jobs', 'market_type')
    op.drop_column('custom_ml_models', 'market_type')
    # ### end Alembic commands ###
