"""Add options activity models

Revision ID: 1a2b3c4d5e6f
Revises: 34a5bbff8136, f389f6bb9761, optimize_market_data, 55f8037c51cd
Create Date: 2024-03-29 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = ('34a5bbff8136', 'f389f6bb9761', 'optimize_market_data', '55f8037c51cd')  # Merge all 4 heads
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('option_type', sa.String(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_trades_id'), 'option_trades', ['id'], unique=False)
    op.create_index(op.f('ix_option_trades_ticker'), 'option_trades', ['ticker'], unique=False)
    
    op.create_table('option_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('put_call_ratio', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_sentiment_id'), 'option_sentiment', ['id'], unique=False)
    op.create_index(op.f('ix_option_sentiment_symbol'), 'option_sentiment', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_sentiment_symbol'), table_name='option_sentiment')
    op.drop_index(op.f('ix_option_sentiment_id'), table_name='option_sentiment')
    op.drop_table('option_sentiment')
    op.drop_index(op.f('ix_option_trades_ticker'), table_name='option_trades')
    op.drop_index(op.f('ix_option_trades_id'), table_name='option_trades')
    op.drop_table('option_trades')
    # ### end Alembic commands ###
