"""add_use_master_bot

Revision ID: 1d65ecace55c
Revises: 14e5d2bfe6f6
Create Date: 2026-09-01 14:21:55.108039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d65ecace55c'
down_revision: Union[str, Sequence[str], None] = '14e5d2bfe6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_settings', sa.Column('use_master_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_settings', 'use_master_bot')
    # ### end Alembic commands ###
