"""add_sentiment_metrics

Revision ID: 231da2a090dc
Revises: 9005a24ed3f3
Create Date: 2026-01-05 17:39:30.817353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231da2a090dc'
down_revision: Union[str, Sequence[str], None] = '9005a24ed3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_history', sa.Column('sentiment_momentum', sa.Float(), nullable=True))
    op.add_column('sentiment_history', sa.Column('social_volume', sa.Integer(), nullable=True))
    op.add_column('sentiment_history', sa.Column('top_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentiment_history', 'top_source')
    op.drop_column('sentiment_history', 'social_volume')
    op.drop_column('sentiment_history', 'sentiment_momentum')
    # ### end Alembic commands ###
