"""Add analyst models

Revision ID: 2425e74621f6
Revises: 5e2e9b9f1a9e
Create Date: 2026-02-21 14:46:06.018183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2425e74621f6'
down_revision: Union[str, Sequence[str], None] = '5e2e9b9f1a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('firm_name', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating_action', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('price_target', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_ratings_id'), 'analyst_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_analyst_ratings_ticker'), 'analyst_ratings', ['ticker'], unique=False)
    op.create_table('research_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('report_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_reports_id'), 'research_reports', ['id'], unique=False)
    op.create_index(op.f('ix_research_reports_ticker'), 'research_reports', ['ticker'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AnalystRating',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('strongBuy', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('buy', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('hold', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('sell', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('strongSell', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('consensus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('targetHigh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('targetLow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('targetMean', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('AnalystRating_pkey'))
    )
    op.create_index(op.f('AnalystRating_symbol_key'), 'AnalystRating', ['symbol'], unique=True)
    op.drop_index(op.f('ix_research_reports_ticker'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_id'), table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_analyst_ratings_ticker'), table_name='analyst_ratings')
    op.drop_index(op.f('ix_analyst_ratings_id'), table_name='analyst_ratings')
    op.drop_table('analyst_ratings')
    # ### end Alembic commands ###
