"""Add config to forex bots

Revision ID: 311973220153
Revises: bf63bf2bf799
Create Date: 2026-06-27 19:56:23.142706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311973220153'
down_revision: Union[str, Sequence[str], None] = 'bf63bf2bf799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forex_bots', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forex_bots', 'config')
    # ### end Alembic commands ###
