"""add_influencer_track_table

Revision ID: 34a5bbff8136
Revises: f1fea7941fbf
Create Date: 2026-01-18 17:41:08.249063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a5bbff8136'
down_revision: Union[str, Sequence[str], None] = 'f1fea7941fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('last_sentiment', sa.String(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencer_track_handle'), 'influencer_track', ['handle'], unique=False)
    op.create_index(op.f('ix_influencer_track_id'), 'influencer_track', ['id'], unique=False)
    op.create_index(op.f('ix_influencer_track_name'), 'influencer_track', ['name'], unique=False)
    op.create_table('social_dominance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('dominance_percentage', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_dominance_asset'), 'social_dominance', ['asset'], unique=False)
    op.create_index(op.f('ix_social_dominance_id'), 'social_dominance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_dominance_id'), table_name='social_dominance')
    op.drop_index(op.f('ix_social_dominance_asset'), table_name='social_dominance')
    op.drop_table('social_dominance')
    op.drop_index(op.f('ix_influencer_track_name'), table_name='influencer_track')
    op.drop_index(op.f('ix_influencer_track_id'), table_name='influencer_track')
    op.drop_index(op.f('ix_influencer_track_handle'), table_name='influencer_track')
    op.drop_table('influencer_track')
    # ### end Alembic commands ###
