"""add_is_paper_trading

Revision ID: 36e898fe86f8
Revises: d8cabb8d192b
Create Date: 2026-01-15 18:16:37.888617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e898fe86f8'
down_revision: Union[str, Sequence[str], None] = 'd8cabb8d192b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitrage_bots', sa.Column('is_paper_trading', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arbitrage_bots', 'is_paper_trading')
    # ### end Alembic commands ###
