"""Add sor_threshold

Revision ID: 3f2ce1f56b13
Revises: 0eea573d5fc5
Create Date: 2026-01-17 05:17:51.669412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2ce1f56b13'
down_revision: Union[str, Sequence[str], None] = '0eea573d5fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitrage_bots', sa.Column('sor_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arbitrage_bots', 'sor_threshold')
    # ### end Alembic commands ###
