"""add forex models

Revision ID: 4684428e479c
Revises: d36f2fc8e95e
Create Date: 2026-06-27 09:21:44.027839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4684428e479c'
down_revision: Union[str, Sequence[str], None] = 'd36f2fc8e95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forex_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pair', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('max_drawdown_percent', sa.Float(), nullable=True),
    sa.Column('use_news_filter', sa.Boolean(), nullable=True),
    sa.Column('max_spread_pips', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_pips', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_bots_id'), 'forex_bots', ['id'], unique=False)
    op.create_index(op.f('ix_forex_bots_name'), 'forex_bots', ['name'], unique=False)
    op.create_index(op.f('ix_forex_bots_pair'), 'forex_bots', ['pair'], unique=False)
    op.create_table('forex_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('pair', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('pips_gained', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('swap_fee', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_trades_bot_id'), 'forex_trades', ['bot_id'], unique=False)
    op.create_index(op.f('ix_forex_trades_id'), 'forex_trades', ['id'], unique=False)
    op.create_index(op.f('ix_forex_trades_pair'), 'forex_trades', ['pair'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forex_trades_pair'), table_name='forex_trades')
    op.drop_index(op.f('ix_forex_trades_id'), table_name='forex_trades')
    op.drop_index(op.f('ix_forex_trades_bot_id'), table_name='forex_trades')
    op.drop_table('forex_trades')
    op.drop_index(op.f('ix_forex_bots_pair'), table_name='forex_bots')
    op.drop_index(op.f('ix_forex_bots_name'), table_name='forex_bots')
    op.drop_index(op.f('ix_forex_bots_id'), table_name='forex_bots')
    op.drop_table('forex_bots')
    # ### end Alembic commands ###
