"""Add AnalysisSignal

Revision ID: 4d90fcd8bc59
Revises: 9999_add_sentiment_history
Create Date: 2026-01-30 14:29:40.571588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d90fcd8bc59'
down_revision: Union[str, Sequence[str], None] = '9999_add_sentiment_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('pattern_name', sa.String(), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('volume_change_pct', sa.Float(), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_signals_id'), 'analysis_signals', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_signals_pattern_name'), 'analysis_signals', ['pattern_name'], unique=False)
    op.create_index(op.f('ix_analysis_signals_symbol'), 'analysis_signals', ['symbol'], unique=False)
    op.drop_table('social_dominance')
    op.drop_table('influencer_track')
    op.drop_table('sentiment_poll')
    op.add_column('education_resources', sa.Column('impact_level', sa.String(), nullable=True))
    op.add_column('education_resources', sa.Column('impact_score', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sentiment_history_id'), 'sentiment_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_history_id'), table_name='sentiment_history')
    op.drop_column('education_resources', 'impact_score')
    op.drop_column('education_resources', 'impact_level')
    op.create_table('sentiment_poll',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('vote_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sentiment_poll_pkey'))
    )
    op.create_index(op.f('ix_sentiment_poll_user_id'), 'sentiment_poll', ['user_id'], unique=False)
    op.create_index(op.f('ix_sentiment_poll_symbol'), 'sentiment_poll', ['symbol'], unique=False)
    op.create_index(op.f('ix_sentiment_poll_ip_address'), 'sentiment_poll', ['ip_address'], unique=False)
    op.create_index(op.f('ix_sentiment_poll_id'), 'sentiment_poll', ['id'], unique=False)
    op.create_table('influencer_track',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('handle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_sentiment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reliability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('influencer_track_pkey'))
    )
    op.create_index(op.f('ix_influencer_track_name'), 'influencer_track', ['name'], unique=False)
    op.create_index(op.f('ix_influencer_track_id'), 'influencer_track', ['id'], unique=False)
    op.create_index(op.f('ix_influencer_track_handle'), 'influencer_track', ['handle'], unique=False)
    op.create_table('social_dominance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dominance_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('social_dominance_pkey'))
    )
    op.create_index(op.f('ix_social_dominance_id'), 'social_dominance', ['id'], unique=False)
    op.create_index(op.f('ix_social_dominance_asset'), 'social_dominance', ['asset'], unique=False)
    op.drop_index(op.f('ix_analysis_signals_symbol'), table_name='analysis_signals')
    op.drop_index(op.f('ix_analysis_signals_pattern_name'), table_name='analysis_signals')
    op.drop_index(op.f('ix_analysis_signals_id'), table_name='analysis_signals')
    op.drop_table('analysis_signals')
    # ### end Alembic commands ###
