"""add_whale_alert_table

Revision ID: 51755f96d663
Revises: 6dca0b577d83
Create Date: 2026-01-17 06:35:20.019238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51755f96d663'
down_revision: Union[str, Sequence[str], None] = '6dca0b577d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whale_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whale_alerts_id'), 'whale_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_whale_alerts_symbol'), 'whale_alerts', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whale_alerts_symbol'), table_name='whale_alerts')
    op.drop_index(op.f('ix_whale_alerts_id'), table_name='whale_alerts')
    op.drop_table('whale_alerts')
    # ### end Alembic commands ###
