"""Add SentimentPoll table

Revision ID: 55f8037c51cd
Revises: 4d90fcd8bc59
Create Date: 2026-01-30 14:56:04.486284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f8037c51cd'
down_revision: Union[str, Sequence[str], None] = '4d90fcd8bc59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('last_sentiment', sa.String(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencer_track_handle'), 'influencer_track', ['handle'], unique=False)
    op.create_index(op.f('ix_influencer_track_id'), 'influencer_track', ['id'], unique=False)
    op.create_index(op.f('ix_influencer_track_name'), 'influencer_track', ['name'], unique=False)
    op.create_table('sentiment_poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('vote_type', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_poll_id'), 'sentiment_poll', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_poll_ip_address'), 'sentiment_poll', ['ip_address'], unique=False)
    op.create_index(op.f('ix_sentiment_poll_symbol'), 'sentiment_poll', ['symbol'], unique=False)
    op.create_index(op.f('ix_sentiment_poll_user_id'), 'sentiment_poll', ['user_id'], unique=False)
    op.create_table('social_dominance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('dominance_percentage', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_dominance_asset'), 'social_dominance', ['asset'], unique=False)
    op.create_index(op.f('ix_social_dominance_id'), 'social_dominance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_dominance_id'), table_name='social_dominance')
    op.drop_index(op.f('ix_social_dominance_asset'), table_name='social_dominance')
    op.drop_table('social_dominance')
    op.drop_index(op.f('ix_sentiment_poll_user_id'), table_name='sentiment_poll')
    op.drop_index(op.f('ix_sentiment_poll_symbol'), table_name='sentiment_poll')
    op.drop_index(op.f('ix_sentiment_poll_ip_address'), table_name='sentiment_poll')
    op.drop_index(op.f('ix_sentiment_poll_id'), table_name='sentiment_poll')
    op.drop_table('sentiment_poll')
    op.drop_index(op.f('ix_influencer_track_name'), table_name='influencer_track')
    op.drop_index(op.f('ix_influencer_track_id'), table_name='influencer_track')
    op.drop_index(op.f('ix_influencer_track_handle'), table_name='influencer_track')
    op.drop_table('influencer_track')
    # ### end Alembic commands ###
