"""add insider table correct

Revision ID: 5672d52c767b
Revises: d8f3bb936460
Create Date: 2026-02-16 18:29:44.163590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5672d52c767b'
down_revision: Union[str, Sequence[str], None] = 'd8f3bb936460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insider_filings',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('insider_name', sa.String(), nullable=False),
    sa.Column('insider_role', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('share_price', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_filings_id'), 'insider_filings', ['id'], unique=False)
    op.create_index(op.f('ix_insider_filings_ticker'), 'insider_filings', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insider_filings_ticker'), table_name='insider_filings')
    op.drop_index(op.f('ix_insider_filings_id'), table_name='insider_filings')
    op.drop_table('insider_filings')
    # ### end Alembic commands ###
