"""add_institutional_tables

Revision ID: 5e2e9b9f1a9e
Revises: 5672d52c767b
Create Date: 2026-02-18 03:40:05.044154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2e9b9f1a9e'
down_revision: Union[str, Sequence[str], None] = '5672d52c767b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('cik', sa.String(), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_funds_cik'), 'institutional_funds', ['cik'], unique=True)
    op.create_index(op.f('ix_institutional_funds_id'), 'institutional_funds', ['id'], unique=False)
    op.create_index(op.f('ix_institutional_funds_manager'), 'institutional_funds', ['manager'], unique=False)
    op.create_index(op.f('ix_institutional_funds_name'), 'institutional_funds', ['name'], unique=False)
    op.create_table('fund_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('percent_portfolio', sa.Float(), nullable=True),
    sa.Column('date_reported', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['institutional_funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_holdings_id'), 'fund_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_fund_holdings_ticker'), 'fund_holdings', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_holdings_ticker'), table_name='fund_holdings')
    op.drop_index(op.f('ix_fund_holdings_id'), table_name='fund_holdings')
    op.drop_table('fund_holdings')
    op.drop_index(op.f('ix_institutional_funds_name'), table_name='institutional_funds')
    op.drop_index(op.f('ix_institutional_funds_manager'), table_name='institutional_funds')
    op.drop_index(op.f('ix_institutional_funds_id'), table_name='institutional_funds')
    op.drop_index(op.f('ix_institutional_funds_cik'), table_name='institutional_funds')
    op.drop_table('institutional_funds')
    # ### end Alembic commands ###
