"""Add sor_enabled

Revision ID: 620fffc88bad
Revises: 3f2ce1f56b13
Create Date: 2026-01-17 05:25:13.516077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620fffc88bad'
down_revision: Union[str, Sequence[str], None] = '3f2ce1f56b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitrage_bots', sa.Column('sor_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arbitrage_bots', 'sor_enabled')
    # ### end Alembic commands ###
