"""add_retail_and_smart_money_scores

Revision ID: 6c3d47a752fa
Revises: 231da2a090dc
Create Date: 2026-01-08 18:12:52.283501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3d47a752fa'
down_revision: Union[str, Sequence[str], None] = '231da2a090dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_history', sa.Column('retail_score', sa.Float(), nullable=True))
    op.add_column('sentiment_history', sa.Column('smart_money_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentiment_history', 'smart_money_score')
    op.drop_column('sentiment_history', 'retail_score')
    # ### end Alembic commands ###
