"""add_ip_whitelist

Revision ID: 6dca0b577d83
Revises: 620fffc88bad
Create Date: 2026-01-17 06:08:08.135515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dca0b577d83'
down_revision: Union[str, Sequence[str], None] = '620fffc88bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowed_ips', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('is_ip_whitelist_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_ip_whitelist_enabled')
    op.drop_column('users', 'allowed_ips')
    # ### end Alembic commands ###
