"""Add passphrase to api_keys

Revision ID: 6f760552ef2c
Revises: 7edfd2ff7ff3
Create Date: 2026-01-11 06:18:37.965020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f760552ef2c'
down_revision: Union[str, Sequence[str], None] = '7edfd2ff7ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('passphrase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'passphrase')
    # ### end Alembic commands ###
