"""add model_versions columns

Revision ID: 8d402fd5d244
Revises: abcd1234efgh
Create Date: 2026-05-09 07:14:50.289614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d402fd5d244'
down_revision: Union[str, Sequence[str], None] = 'abcd1234efgh'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE model_versions ADD COLUMN IF NOT EXISTS accuracy FLOAT')
    op.execute('ALTER TABLE model_versions ADD COLUMN IF NOT EXISTS f1_score FLOAT')
    op.execute('ALTER TABLE model_versions ADD COLUMN IF NOT EXISTS latency FLOAT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE model_versions DROP COLUMN IF EXISTS latency')
    op.execute('ALTER TABLE model_versions DROP COLUMN IF EXISTS f1_score')
    op.execute('ALTER TABLE model_versions DROP COLUMN IF EXISTS accuracy')
    # ### end Alembic commands ###
