"""add_grid_paper_fields

Revision ID: 8f2ac2a98e86
Revises: 3588b5b377c6
Create Date: 2026-01-18 03:43:49.992358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2ac2a98e86'
down_revision: Union[str, Sequence[str], None] = '3588b5b377c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['grid_bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grid_orders_id'), 'grid_orders', ['id'], unique=False)
    op.add_column('grid_bots', sa.Column('paper_balance_initial', sa.Float(), nullable=True))
    op.add_column('grid_bots', sa.Column('paper_balance_current', sa.Float(), nullable=True))
    op.add_column('grid_bots', sa.Column('paper_asset_quantity', sa.Float(), nullable=True))
    op.add_column('grid_bots', sa.Column('status_reason', sa.String(), nullable=True))
    op.add_column('grid_bots', sa.Column('total_profit', sa.Float(), nullable=True))
    op.add_column('grid_bots', sa.Column('unrealized_profit', sa.Float(), nullable=True))
    op.add_column('grid_bots', sa.Column('current_cycle_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_grid_bots_is_paper_trading'), 'grid_bots', ['is_paper_trading'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grid_bots_is_paper_trading'), table_name='grid_bots')
    op.drop_column('grid_bots', 'current_cycle_count')
    op.drop_column('grid_bots', 'unrealized_profit')
    op.drop_column('grid_bots', 'total_profit')
    op.drop_column('grid_bots', 'status_reason')
    op.drop_column('grid_bots', 'paper_asset_quantity')
    op.drop_column('grid_bots', 'paper_balance_current')
    op.drop_column('grid_bots', 'paper_balance_initial')
    op.drop_index(op.f('ix_grid_orders_id'), table_name='grid_orders')
    op.drop_table('grid_orders')
    # ### end Alembic commands ###
