"""add_sentiment_history

Revision ID: 9005a24ed3f3
Revises: a1b2c3d4e5f6
Create Date: 2026-01-05 06:43:31.485977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9005a24ed3f3'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('news_count', sa.Integer(), nullable=True),
    sa.Column('dominant_sentiment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_history_id'), 'sentiment_history', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_history_timestamp'), 'sentiment_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_history_timestamp'), table_name='sentiment_history')
    op.drop_index(op.f('ix_sentiment_history_id'), table_name='sentiment_history')
    op.drop_table('sentiment_history')
    # ### end Alembic commands ###
