"""Add data_lookback_hours to CustomMLModel

Revision ID: 90dedac036a4
Revises: 1092cad39267
Create Date: 2026-05-02 16:08:37.170707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90dedac036a4'
down_revision: Union[str, Sequence[str], None] = '1092cad39267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_ml_models', sa.Column('data_lookback_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_ml_models', 'data_lookback_hours')
    # ### end Alembic commands ###
