"""add_auto_balance_to_bot

Revision ID: 9af3876697ae
Revises: 51755f96d663
Create Date: 2026-01-17 08:31:12.069652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af3876697ae'
down_revision: Union[str, Sequence[str], None] = '51755f96d663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitrage_bots', sa.Column('auto_balance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arbitrage_bots', 'auto_balance')
    # ### end Alembic commands ###
