"""Add education models

Revision ID: a237e874be23
Revises: 752a1a114fc8
Create Date: 2026-01-12 16:57:49.758119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a237e874be23'
down_revision: Union[str, Sequence[str], None] = '752a1a114fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education_resources', sa.Column('level', sa.String(), nullable=True))
    op.add_column('education_resources', sa.Column('track_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_education_resources_level'), 'education_resources', ['level'], unique=False)
    op.drop_column('education_resources', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education_resources', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_education_resources_level'), table_name='education_resources')
    op.drop_column('education_resources', 'track_order')
    op.drop_column('education_resources', 'level')
    # ### end Alembic commands ###
