"""Add OrderBookSnapshot

Revision ID: a93c577e47cb
Revises: 0d45fc594824
Create Date: 2026-03-06 23:40:32.863214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a93c577e47cb'
down_revision: Union[str, Sequence[str], None] = '0d45fc594824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('asks', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orderbook_snapshot_lookup', 'orderbook_snapshots', ['symbol', 'exchange', 'timestamp'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_exchange'), 'orderbook_snapshots', ['exchange'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_id'), 'orderbook_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_symbol'), 'orderbook_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_timestamp'), 'orderbook_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderbook_snapshots_timestamp'), table_name='orderbook_snapshots')
    op.drop_index(op.f('ix_orderbook_snapshots_symbol'), table_name='orderbook_snapshots')
    op.drop_index(op.f('ix_orderbook_snapshots_id'), table_name='orderbook_snapshots')
    op.drop_index(op.f('ix_orderbook_snapshots_exchange'), table_name='orderbook_snapshots')
    op.drop_index('idx_orderbook_snapshot_lookup', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    # ### end Alembic commands ###
