"""add explainability column

Revision ID: abcd1234efgh
Revises: 09d8b8bed6b3
Create Date: 2026-05-09 12:01:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcd1234efgh'
down_revision = 'e3eb108fbb96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('explainability', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'explainability')
    # ### end Alembic commands ###
