"""Add session columns

Revision ID: b0dcc68dc8aa
Revises: c6101270710c
Create Date: 2026-04-02 09:59:50.966510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dcc68dc8aa'
down_revision: Union[str, Sequence[str], None] = 'c6101270710c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_settings', sa.Column('notify_sydney', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('notify_tokyo', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('notify_london', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('notify_new_york', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('alert_session_start', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('alert_price_data', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('alert_overlap', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('alert_weekly_summary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_settings', 'alert_weekly_summary')
    op.drop_column('notification_settings', 'alert_overlap')
    op.drop_column('notification_settings', 'alert_price_data')
    op.drop_column('notification_settings', 'alert_session_start')
    op.drop_column('notification_settings', 'notify_new_york')
    op.drop_column('notification_settings', 'notify_london')
    op.drop_column('notification_settings', 'notify_tokyo')
    op.drop_column('notification_settings', 'notify_sydney')
    # ### end Alembic commands ###
