"""Add alert_server_errors to NotificationSettings

Revision ID: b90b8bdf8159
Revises: b0dcc68dc8aa
Create Date: 2026-04-02 20:30:39.982865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90b8bdf8159'
down_revision: Union[str, Sequence[str], None] = 'b0dcc68dc8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_settings', sa.Column('alert_server_errors', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_settings', 'alert_server_errors')
    # ### end Alembic commands ###
