"""Add default_take_profit and default_stop_loss to ForexBot

Revision ID: bf63bf2bf799
Revises: 4684428e479c
Create Date: 2026-06-27 18:52:10.917524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf63bf2bf799'
down_revision: Union[str, Sequence[str], None] = '4684428e479c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forex_bots', sa.Column('default_take_profit', sa.Float(), nullable=True))
    op.add_column('forex_bots', sa.Column('default_stop_loss', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forex_bots', 'default_stop_loss')
    op.drop_column('forex_bots', 'default_take_profit')
    # ### end Alembic commands ###
