"""add_trailing_stop

Revision ID: c16fcc153b85
Revises: aeefd8387b36
Create Date: 2026-01-16 16:35:39.437624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16fcc153b85'
down_revision: Union[str, Sequence[str], None] = 'aeefd8387b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arbitrage_bots', sa.Column('trailing_stop_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arbitrage_bots', 'trailing_stop_percentage')
    # ### end Alembic commands ###
