"""add_is_paper_trading_to_bot

Revision ID: c4000f72727e
Revises: d5cab4d39a9c
Create Date: 2026-01-17 09:09:47.588412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4000f72727e'
down_revision: Union[str, Sequence[str], None] = 'd5cab4d39a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('is_paper_trading', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'is_paper_trading')
    # ### end Alembic commands ###
