"""Add exchange and trade configs

Revision ID: c5d9cc935a7a
Revises: 82356c6ce505
Create Date: 2025-12-09 08:08:16.680488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d9cc935a7a'
down_revision: Union[str, Sequence[str], None] = '82356c6ce505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('exchange', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('trade_value', sa.Float(), nullable=True))
    op.add_column('bots', sa.Column('trade_unit', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('api_key_id', sa.String(), nullable=True))
    op.drop_column('bots', 'initial_capital')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('initial_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('bots', 'api_key_id')
    op.drop_column('bots', 'trade_unit')
    op.drop_column('bots', 'trade_value')
    op.drop_column('bots', 'exchange')
    # ### end Alembic commands ###
