"""Add PredictionLog

Revision ID: caa68a11b933
Revises: d74835454012
Create Date: 2026-05-17 04:48:51.382585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa68a11b933'
down_revision: Union[str, Sequence[str], None] = 'd74835454012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('predicted_signal', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actual_outcome_price', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_logs_id'), 'prediction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_logs_model_id'), 'prediction_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_prediction_logs_symbol'), 'prediction_logs', ['symbol'], unique=False)
    op.create_index(op.f('ix_prediction_logs_timestamp'), 'prediction_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_logs_timestamp'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_symbol'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_model_id'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_id'), table_name='prediction_logs')
    op.drop_table('prediction_logs')
    # ### end Alembic commands ###
