"""Add automated education resources

Revision ID: ce10a085e88f
Revises: 6f760552ef2c
Create Date: 2026-01-12 13:33:24.452660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce10a085e88f'
down_revision: Union[str, Sequence[str], None] = '6f760552ef2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_education_resources_category'), 'education_resources', ['category'], unique=False)
    op.create_index(op.f('ix_education_resources_id'), 'education_resources', ['id'], unique=False)
    op.create_index(op.f('ix_education_resources_source'), 'education_resources', ['source'], unique=False)
    op.create_index(op.f('ix_education_resources_title'), 'education_resources', ['title'], unique=False)
    op.create_table('user_education_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['education_resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_education_progress_id'), 'user_education_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_education_progress_id'), table_name='user_education_progress')
    op.drop_table('user_education_progress')
    op.drop_index(op.f('ix_education_resources_title'), table_name='education_resources')
    op.drop_index(op.f('ix_education_resources_source'), table_name='education_resources')
    op.drop_index(op.f('ix_education_resources_id'), table_name='education_resources')
    op.drop_index(op.f('ix_education_resources_category'), table_name='education_resources')
    op.drop_table('education_resources')
    # ### end Alembic commands ###
