"""Add hybrid deep trade features to orderbook_snapshots

Revision ID: d36f2fc8e95e
Revises: ffc5a42b6442
Create Date: 2026-06-09 09:01:43.822714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36f2fc8e95e'
down_revision: Union[str, Sequence[str], None] = 'ffc5a42b6442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderbook_snapshots', sa.Column('trade_count', sa.Integer(), nullable=True))
    op.add_column('orderbook_snapshots', sa.Column('buy_volume', sa.Float(), nullable=True))
    op.add_column('orderbook_snapshots', sa.Column('sell_volume', sa.Float(), nullable=True))
    op.add_column('orderbook_snapshots', sa.Column('trade_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderbook_snapshots', 'trade_price')
    op.drop_column('orderbook_snapshots', 'sell_volume')
    op.drop_column('orderbook_snapshots', 'buy_volume')
    op.drop_column('orderbook_snapshots', 'trade_count')
    # ### end Alembic commands ###
