"""make_api_keys_nullable

Revision ID: d5cab4d39a9c
Revises: 9af3876697ae
Create Date: 2026-01-17 08:50:47.494352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5cab4d39a9c'
down_revision: Union[str, Sequence[str], None] = '9af3876697ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arbitrage_bots', 'api_key_a_label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('arbitrage_bots', 'api_key_b_label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arbitrage_bots', 'api_key_b_label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('arbitrage_bots', 'api_key_a_label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
