"""Add TokenUnlockEvent

Revision ID: d8f3bb936460
Revises: 1a2b3c4d5e6f
Create Date: 2026-02-16 08:17:37.379922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f3bb936460'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # শুধু নতুন token_unlock_events টেবিল তৈরি হবে
    op.create_table('token_unlock_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('token_name', sa.String(), nullable=True),
    sa.Column('unlock_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('circulating_supply_pct', sa.Float(), nullable=True),
    sa.Column('vesting_schedule', sa.JSON(), nullable=True),
    sa.Column('allocations', sa.JSON(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_unlock_events_id'), 'token_unlock_events', ['id'], unique=False)
    op.create_index(op.f('ix_token_unlock_events_symbol'), 'token_unlock_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_token_unlock_events_unlock_date'), 'token_unlock_events', ['unlock_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # শুধু token_unlock_events টেবিল ড্রপ হবে
    op.drop_index(op.f('ix_token_unlock_events_unlock_date'), table_name='token_unlock_events')
    op.drop_index(op.f('ix_token_unlock_events_symbol'), table_name='token_unlock_events')
    op.drop_index(op.f('ix_token_unlock_events_id'), table_name='token_unlock_events')
    op.drop_table('token_unlock_events')
    # ### end Alembic commands ###
