"""add_arbitrage_bot_table

Revision ID: ea358d0be52e
Revises: a237e874be23
Create Date: 2026-01-13 12:54:49.656824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea358d0be52e'
down_revision: Union[str, Sequence[str], None] = 'a237e874be23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbitrage_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('exchange_a', sa.String(), nullable=False),
    sa.Column('api_key_a_label', sa.String(), nullable=False),
    sa.Column('exchange_b', sa.String(), nullable=False),
    sa.Column('api_key_b_label', sa.String(), nullable=False),
    sa.Column('min_spread', sa.Float(), nullable=True),
    sa.Column('trade_amount', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arbitrage_bots_id'), 'arbitrage_bots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arbitrage_bots_id'), table_name='arbitrage_bots')
    op.drop_table('arbitrage_bots')
    # ### end Alembic commands ###
