"""Add bot model

Revision ID: f12e3ed472d1
Revises: optimize_market_data
Create Date: 2025-12-09 02:51:04.618224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12e3ed472d1'
down_revision: Union[str, Sequence[str], None] = 'optimize_market_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_percent', sa.Float(), nullable=True),
    sa.Column('initial_capital', sa.Float(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_regime_aware', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_id'), 'bots', ['id'], unique=False)
    op.create_index(op.f('ix_bots_name'), 'bots', ['name'], unique=False)
    op.drop_index(op.f('ix_market_data_exchange'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_timeframe'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_constraint(op.f('unique_candle'), 'market_data', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_candle'), 'market_data', ['exchange', 'symbol', 'timeframe', 'timestamp'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_timeframe'), 'market_data', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_exchange'), 'market_data', ['exchange'], unique=False)
    op.drop_index(op.f('ix_bots_name'), table_name='bots')
    op.drop_index(op.f('ix_bots_id'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
